### PR TITLE
update dependencies

### PR DESCRIPTION
**Pull request by eminarican**

### CODE REVIEW

**Review by nin-jin — APPROVED** [review]

**Comment by nin-jin** [comment]
Do you use this module for something?

**Comment by eminarican** [comment]
Yeah I'll use it in my some private projects

**Comment by nin-jin** [comment]
Can you help me to port this library from `vibe` to `std`?

**Comment by eminarican** [comment]
Sorry I've upcoming exams currently so I should study for them :/

**Comment by nin-jin** [comment]
Good luck with the exams.

**Comment by eminarican** [comment]
Thanks ^^

**Pull request merged**
